import Header from 'components/header/Header'
import Head from 'next/head'
import Footer from 'components/sections/footer'
import ReadyToSellPage from 'components/sections/readyToSell'

const Index = () => {
    return (
        <div>
            <Head>
                <title>Wheeliyo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className="relative">
                <img
                    alt="bg"
                    className="w-screen"
                    src="/assets/privacy-policy-bg.svg"
                />
                <div className="absolute-center text-white text-center">
                    <h1 className="xl:text-3xl text-base xl:mb-2 md:text-xl">
                        Refund Policy
                    </h1>
                </div>
            </div>
            <div className="flex justify-center items-center px-4 lg:px-10">
                <div className="w-[1064px] min-h-[200px] bg-white rounded-3xl shadow-xl px-[28px] py-[34px]">
                    <div>
                        <h1 className="text-secondary text-xl font-bold pt-4">
                            Refund Policy
                        </h1>
                        <div className="flex-col flex gap-5 mt-4  text-base md:text-lg">
                            <p>
                                Thank you for choosing Wheeliyo. We strive to
                                offer a seamless and valuable experience to all
                                our users. As with any online transaction, some
                                terms and conditions govern our Refund Policy.
                                By purchasing any service or plan on Wheeliyo,
                                you agree to our Terms & Conditions and this
                                refund policy.
                            </p>
                            <p>Our refund policy is as follows:</p>
                            <p>
                                You acknowledge that the services or plans
                                purchased from Wheeliyo are non-transferable and
                                non-refundable.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <section id="get-in-touch" className="pt-[47px]">
                <ReadyToSellPage />
            </section>
            <section className="lg:h-[195px] bottom-0">
                <Footer />
            </section>
        </div>
    )
}

export default Index
