import Header from 'components/header/Header'
import Head from 'next/head'
import Footer from 'components/sections/footer'
import ReadyToSellPage from 'components/sections/readyToSell'

const TermsAndConditions = () => {
    return (
        <div>
            <Head>
                <title>Wheeliyo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className="relative">
                <img
                    alt="bg"
                    className="w-screen"
                    src="/assets/privacy-policy-bg.svg"
                />
                <div className="absolute-center text-white text-center">
                    <h1 className="xl:text-3xl text-base xl:mb-2 md:text-xl">
                        Terms and conditions
                    </h1>
                </div>
            </div>
            <div className="flex justify-center items-center px-4 lg:px-10">
                <div className="w-[1064px] min-h-[200px] bg-white rounded-3xl shadow-xl px-[28px] py-[34px]">
                    <div>
                        <h1 className="text-secondary text-xl font-bold pt-4">
                            Terms and conditions
                        </h1>
                        <div className="flex-col flex gap-5 mt-4  text-base md:text-lg">
                            <h1 className="text-[#231F20]">
                                By using this website, you accept the following
                                Terms & Conditions
                            </h1>
                            <h1 className="text-[#231F20]">
                                When using this Website, You may be subject to
                                other posted terms and guidelines applicable to
                                certain services available on this website.
                            </h1>
                            <h1 className="text-[#231F20]">
                                All terms and guidelines on this website,
                                including our Privacy Policy, are part of these
                                Terms & Conditions.
                            </h1>
                            <h1 className="text-[#231F20]">
                                Unless explicitly stated otherwise, any features
                                or services available at any time on this
                                website are subject to these Terms & Conditions.
                            </h1>
                            <h1 className="text-[#231F20]">
                                Accessing this website in any manner, even
                                through automated means, constitutes your use of
                                the website and your agreement to be bound by
                                these Terms & Conditions.
                            </h1>
                            <h1 className="text-[#231F20]">
                                Wheeliyo may change the Terms & Conditions from
                                time to time.
                            </h1>
                            <h1 className="text-[#231F20]">
                                Your continued use of this website after the
                                posted effective date constitutes your agreement
                                to be bound by these Terms & conditions as
                                modified, except that modifications do not apply
                                to any dispute arising before their effective
                                date.
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
            <section id="get-in-touch" className="pt-[47px]">
                <ReadyToSellPage />
            </section>
            <section className="lg:h-[195px] bottom-0">
                <Footer />
            </section>
        </div>
    )
}

export default TermsAndConditions
