import countriesServices from 'core/services/countries.services'

export default async function seedCountries() {
    await countriesServices.bulkInsert([
        {
            code: 'AD',
            label: 'Andorra',
            phone: '376',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AE',
            label: 'United Arab Emirates',
            phone: '971',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AF',
            label: 'Afghanistan',
            phone: '93',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AG',
            label: 'Antigua and Barbuda',
            phone: '1-268',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AI',
            label: 'Anguilla',
            phone: '1-264',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AL',
            label: 'Albania',
            phone: '355',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AM',
            label: 'Armenia',
            phone: '374',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AO',
            label: 'Angola',
            phone: '244',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AQ',
            label: 'Antarctica',
            phone: '672',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AR',
            label: 'Argentina',
            phone: '54',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AS',
            label: 'American Samoa',
            phone: '1-684',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AT',
            label: 'Austria',
            phone: '43',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AU',
            label: 'Australia',
            phone: '61',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AW',
            label: 'Aruba',
            phone: '297',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AX',
            label: 'Alland Islands',
            phone: '358',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'AZ',
            label: 'Azerbaijan',
            phone: '994',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BA',
            label: 'Bosnia and Herzegovina',
            phone: '387',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BB',
            label: 'Barbados',
            phone: '1-246',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BD',
            label: 'Bangladesh',
            phone: '880',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BE',
            label: 'Belgium',
            phone: '32',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BF',
            label: 'Burkina Faso',
            phone: '226',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BG',
            label: 'Bulgaria',
            phone: '359',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BH',
            label: 'Bahrain',
            phone: '973',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BI',
            label: 'Burundi',
            phone: '257',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BJ',
            label: 'Benin',
            phone: '229',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BL',
            label: 'Saint Barthelemy',
            phone: '590',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BM',
            label: 'Bermuda',
            phone: '1-441',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BN',
            label: 'Brunei Darussalam',
            phone: '673',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BO',
            label: 'Bolivia',
            phone: '591',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BR',
            label: 'Brazil',
            phone: '55',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BS',
            label: 'Bahamas',
            phone: '1-242',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BT',
            label: 'Bhutan',
            phone: '975',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BV',
            label: 'Bouvet Island',
            phone: '47',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BW',
            label: 'Botswana',
            phone: '267',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BY',
            label: 'Belarus',
            phone: '375',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'BZ',
            label: 'Belize',
            phone: '501',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CA',
            label: 'Canada',
            phone: '1',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CC',
            label: 'Cocos (Keeling) Islands',
            phone: '61',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CD',
            label: 'Congo, Democratic Republic of the',
            phone: '243',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CF',
            label: 'Central African Republic',
            phone: '236',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CG',
            label: 'Congo, Republic of the',
            phone: '242',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CH',
            label: 'Switzerland',
            phone: '41',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CI',
            label: "Cote d'Ivoire",
            phone: '225',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CK',
            label: 'Cook Islands',
            phone: '682',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CL',
            label: 'Chile',
            phone: '56',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CM',
            label: 'Cameroon',
            phone: '237',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CN',
            label: 'China',
            phone: '86',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CO',
            label: 'Colombia',
            phone: '57',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CR',
            label: 'Costa Rica',
            phone: '506',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CU',
            label: 'Cuba',
            phone: '53',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CV',
            label: 'Cape Verde',
            phone: '238',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CW',
            label: 'Curacao',
            phone: '599',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CX',
            label: 'Christmas Island',
            phone: '61',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CY',
            label: 'Cyprus',
            phone: '357',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'CZ',
            label: 'Czech Republic',
            phone: '420',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'DE',
            label: 'Germany',
            phone: '49',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'DJ',
            label: 'Djibouti',
            phone: '253',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'DK',
            label: 'Denmark',
            phone: '45',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'DM',
            label: 'Dominica',
            phone: '1-767',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'DO',
            label: 'Dominican Republic',
            phone: '1-809',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'DZ',
            label: 'Algeria',
            phone: '213',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'EC',
            label: 'Ecuador',
            phone: '593',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'EE',
            label: 'Estonia',
            phone: '372',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'EG',
            label: 'Egypt',
            phone: '20',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'EH',
            label: 'Western Sahara',
            phone: '212',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'ER',
            label: 'Eritrea',
            phone: '291',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'ES',
            label: 'Spain',
            phone: '34',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'ET',
            label: 'Ethiopia',
            phone: '251',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'FI',
            label: 'Finland',
            phone: '358',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'FJ',
            label: 'Fiji',
            phone: '679',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'FK',
            label: 'Falkland Islands (Malvinas)',
            phone: '500',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'FM',
            label: 'Micronesia, Federated States of',
            phone: '691',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'FO',
            label: 'Faroe Islands',
            phone: '298',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'FR',
            label: 'France',
            phone: '33',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GA',
            label: 'Gabon',
            phone: '241',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GB',
            label: 'United Kingdom',
            phone: '44',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GD',
            label: 'Grenada',
            phone: '1-473',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GE',
            label: 'Georgia',
            phone: '995',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GF',
            label: 'French Guiana',
            phone: '594',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GG',
            label: 'Guernsey',
            phone: '44',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GH',
            label: 'Ghana',
            phone: '233',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GI',
            label: 'Gibraltar',
            phone: '350',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GL',
            label: 'Greenland',
            phone: '299',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GM',
            label: 'Gambia',
            phone: '220',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GN',
            label: 'Guinea',
            phone: '224',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GP',
            label: 'Guadeloupe',
            phone: '590',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GQ',
            label: 'Equatorial Guinea',
            phone: '240',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GR',
            label: 'Greece',
            phone: '30',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GS',
            label: 'South Georgia and the South Sandwich Islands',
            phone: '500',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GT',
            label: 'Guatemala',
            phone: '502',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GU',
            label: 'Guam',
            phone: '1-671',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GW',
            label: 'Guinea-Bissau',
            phone: '245',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'GY',
            label: 'Guyana',
            phone: '592',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'HK',
            label: 'Hong Kong',
            phone: '852',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'HM',
            label: 'Heard Island and McDonald Islands',
            phone: '672',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'HN',
            label: 'Honduras',
            phone: '504',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'HR',
            label: 'Croatia',
            phone: '385',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'HT',
            label: 'Haiti',
            phone: '509',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'HU',
            label: 'Hungary',
            phone: '36',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'ID',
            label: 'Indonesia',
            phone: '62',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'IE',
            label: 'Ireland',
            phone: '353',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'IL',
            label: 'Israel',
            phone: '972',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'IM',
            label: 'Isle of Man',
            phone: '44',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'IN',
            label: 'India',
            phone: '91',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'IO',
            label: 'British Indian Ocean Territory',
            phone: '246',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'IQ',
            label: 'Iraq',
            phone: '964',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'IR',
            label: 'Iran, Islamic Republic of',
            phone: '98',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'IS',
            label: 'Iceland',
            phone: '354',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'IT',
            label: 'Italy',
            phone: '39',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'JE',
            label: 'Jersey',
            phone: '44',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'JM',
            label: 'Jamaica',
            phone: '1-876',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'JO',
            label: 'Jordan',
            phone: '962',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'JP',
            label: 'Japan',
            phone: '81',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'KE',
            label: 'Kenya',
            phone: '254',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'KG',
            label: 'Kyrgyzstan',
            phone: '996',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'KH',
            label: 'Cambodia',
            phone: '855',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'KI',
            label: 'Kiribati',
            phone: '686',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'KM',
            label: 'Comoros',
            phone: '269',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'KN',
            label: 'Saint Kitts and Nevis',
            phone: '1-869',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'KP',
            label: "Korea, Democratic People's Republic of",
            phone: '850',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'KR',
            label: 'Korea, Republic of',
            phone: '82',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'KW',
            label: 'Kuwait',
            phone: '965',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'KY',
            label: 'Cayman Islands',
            phone: '1-345',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'KZ',
            label: 'Kazakhstan',
            phone: '7',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'LA',
            label: "Lao People's Democratic Republic",
            phone: '856',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'LB',
            label: 'Lebanon',
            phone: '961',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'LC',
            label: 'Saint Lucia',
            phone: '1-758',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'LI',
            label: 'Liechtenstein',
            phone: '423',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'LK',
            label: 'Sri Lanka',
            phone: '94',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'LR',
            label: 'Liberia',
            phone: '231',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'LS',
            label: 'Lesotho',
            phone: '266',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'LT',
            label: 'Lithuania',
            phone: '370',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'LU',
            label: 'Luxembourg',
            phone: '352',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'LV',
            label: 'Latvia',
            phone: '371',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'LY',
            label: 'Libya',
            phone: '218',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MA',
            label: 'Morocco',
            phone: '212',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MC',
            label: 'Monaco',
            phone: '377',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MD',
            label: 'Moldova, Republic of',
            phone: '373',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'ME',
            label: 'Montenegro',
            phone: '382',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MF',
            label: 'Saint Martin (French part)',
            phone: '590',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MG',
            label: 'Madagascar',
            phone: '261',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MH',
            label: 'Marshall Islands',
            phone: '692',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MK',
            label: 'Macedonia, the Former Yugoslav Republic of',
            phone: '389',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'ML',
            label: 'Mali',
            phone: '223',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MM',
            label: 'Myanmar',
            phone: '95',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MN',
            label: 'Mongolia',
            phone: '976',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MO',
            label: 'Macao',
            phone: '853',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MP',
            label: 'Northern Mariana Islands',
            phone: '1-670',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MQ',
            label: 'Martinique',
            phone: '596',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MR',
            label: 'Mauritania',
            phone: '222',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MS',
            label: 'Montserrat',
            phone: '1-664',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MT',
            label: 'Malta',
            phone: '356',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MU',
            label: 'Mauritius',
            phone: '230',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MV',
            label: 'Maldives',
            phone: '960',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MW',
            label: 'Malawi',
            phone: '265',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MX',
            label: 'Mexico',
            phone: '52',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MY',
            label: 'Malaysia',
            phone: '60',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'MZ',
            label: 'Mozambique',
            phone: '258',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'NA',
            label: 'Namibia',
            phone: '264',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'NC',
            label: 'New Caledonia',
            phone: '687',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'NE',
            label: 'Niger',
            phone: '227',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'NF',
            label: 'Norfolk Island',
            phone: '672',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'NG',
            label: 'Nigeria',
            phone: '234',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'NI',
            label: 'Nicaragua',
            phone: '505',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'NL',
            label: 'Netherlands',
            phone: '31',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'NO',
            label: 'Norway',
            phone: '47',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'NP',
            label: 'Nepal',
            phone: '977',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'NR',
            label: 'Nauru',
            phone: '674',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'NU',
            label: 'Niue',
            phone: '683',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'NZ',
            label: 'New Zealand',
            phone: '64',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'OM',
            label: 'Oman',
            phone: '968',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PA',
            label: 'Panama',
            phone: '507',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PE',
            label: 'Peru',
            phone: '51',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PF',
            label: 'French Polynesia',
            phone: '689',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PG',
            label: 'Papua New Guinea',
            phone: '675',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PH',
            label: 'Philippines',
            phone: '63',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PK',
            label: 'Pakistan',
            phone: '92',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PL',
            label: 'Poland',
            phone: '48',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PM',
            label: 'Saint Pierre and Miquelon',
            phone: '508',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PN',
            label: 'Pitcairn',
            phone: '870',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PR',
            label: 'Puerto Rico',
            phone: '1',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PS',
            label: 'Palestine, State of',
            phone: '970',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PT',
            label: 'Portugal',
            phone: '351',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PW',
            label: 'Palau',
            phone: '680',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'PY',
            label: 'Paraguay',
            phone: '595',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'QA',
            label: 'Qatar',
            phone: '974',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'RE',
            label: 'Reunion',
            phone: '262',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'RO',
            label: 'Romania',
            phone: '40',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'RS',
            label: 'Serbia',
            phone: '381',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'RU',
            label: 'Russian Federation',
            phone: '7',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'RW',
            label: 'Rwanda',
            phone: '250',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SA',
            label: 'Saudi Arabia',
            phone: '966',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SB',
            label: 'Solomon Islands',
            phone: '677',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SC',
            label: 'Seychelles',
            phone: '248',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SD',
            label: 'Sudan',
            phone: '249',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SE',
            label: 'Sweden',
            phone: '46',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SG',
            label: 'Singapore',
            phone: '65',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SH',
            label: 'Saint Helena',
            phone: '290',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SI',
            label: 'Slovenia',
            phone: '386',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SJ',
            label: 'Svalbard and Jan Mayen',
            phone: '47',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SK',
            label: 'Slovakia',
            phone: '421',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SL',
            label: 'Sierra Leone',
            phone: '232',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SM',
            label: 'San Marino',
            phone: '378',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SN',
            label: 'Senegal',
            phone: '221',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SO',
            label: 'Somalia',
            phone: '252',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SR',
            label: 'Suriname',
            phone: '597',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SS',
            label: 'South Sudan',
            phone: '211',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'ST',
            label: 'Sao Tome and Principe',
            phone: '239',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SV',
            label: 'El Salvador',
            phone: '503',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SX',
            label: 'Sint Maarten (Dutch part)',
            phone: '1-721',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SY',
            label: 'Syrian Arab Republic',
            phone: '963',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'SZ',
            label: 'Swaziland',
            phone: '268',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TC',
            label: 'Turks and Caicos Islands',
            phone: '1-649',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TD',
            label: 'Chad',
            phone: '235',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TF',
            label: 'French Southern Territories',
            phone: '262',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TG',
            label: 'Togo',
            phone: '228',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TH',
            label: 'Thailand',
            phone: '66',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TJ',
            label: 'Tajikistan',
            phone: '992',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TK',
            label: 'Tokelau',
            phone: '690',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TL',
            label: 'Timor-Leste',
            phone: '670',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TM',
            label: 'Turkmenistan',
            phone: '993',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TN',
            label: 'Tunisia',
            phone: '216',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TO',
            label: 'Tonga',
            phone: '676',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TR',
            label: 'Turkey',
            phone: '90',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TT',
            label: 'Trinidad and Tobago',
            phone: '1-868',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TV',
            label: 'Tuvalu',
            phone: '688',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TW',
            label: 'Taiwan, Republic of China',
            phone: '886',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'TZ',
            label: 'United Republic of Tanzania',
            phone: '255',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'UA',
            label: 'Ukraine',
            phone: '380',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'UG',
            label: 'Uganda',
            phone: '256',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'US',
            label: 'United States',
            phone: '1',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'UY',
            label: 'Uruguay',
            phone: '598',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'UZ',
            label: 'Uzbekistan',
            phone: '998',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'VA',
            label: 'Holy See (Vatican City State)',
            phone: '379',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'VC',
            label: 'Saint Vincent and the Grenadines',
            phone: '1-784',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'VE',
            label: 'Venezuela',
            phone: '58',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'VG',
            label: 'British Virgin Islands',
            phone: '1-284',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'VI',
            label: 'US Virgin Islands',
            phone: '1-340',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'VN',
            label: 'Vietnam',
            phone: '84',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'VU',
            label: 'Vanuatu',
            phone: '678',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'WF',
            label: 'Wallis and Futuna',
            phone: '681',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'WS',
            label: 'Samoa',
            phone: '685',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'XK',
            label: 'Kosovo',
            phone: '383',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'YE',
            label: 'Yemen',
            phone: '967',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'YT',
            label: 'Mayotte',
            phone: '262',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'ZA',
            label: 'South Africa',
            phone: '27',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'ZM',
            label: 'Zambia',
            phone: '260',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
        {
            code: 'ZW',
            label: 'Zimbabwe',
            phone: '263',
            updatedAt: new Date(),
            createdAt: new Date(),
        },
    ])
}
