import Header from 'components/header/Header'
import Head from 'next/head'
import Footer from 'components/sections/footer'
import ReadyToSellPage from 'components/sections/readyToSell'

const TermsAndConditions = () => {
    return (
        <div>
            <Head>
                <title>Wheeliyo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className="relative">
                <img
                    alt="bg"
                    className="w-screen"
                    src="/assets/privacy-policy-bg.svg"
                />
                <div className="absolute-center text-white text-center">
                    <h1 className="xl:text-3xl text-base xl:mb-2 md:text-xl">
                        About Us
                    </h1>
                </div>
            </div>
            <div className="flex flex-col justify-center items-center px-4 lg:px-10">
                <div className="w-[1064px] min-h-[200px] bg-white rounded-3xl shadow-xl px-[28px] py-[34px] mb-8">
                    <div>
                        <h1 className="text-secondary text-xl font-bold pt-4">
                            About Us
                        </h1>
                        <div className="flex-col flex gap-5 mt-4  text-base md:text-lg">
                            <p>
                                Welcome to Wheeliyo, where selling your car is
                                simple and rewarding. We provide you with the
                                best deals and prices in the market by using
                                up-to-date information. Enter your car details,
                                and you will receive fast, competitive offers
                                with minimal wait time. Our professional team
                                conducts hassle-free, doorstep evaluations to
                                ensure a safe and smooth process, and you will
                                even have the chance to meet potential buyers
                                directly to build trust.
                            </p>
                            <p>
                                At Wheeliyo, we also offer access to a wide
                                range of buyers and valuable tools to enhance
                                your selling experience. Our platform is
                                designed to help you get the most out of your
                                vehicle sale. For a quick and accurate price,
                                enter your car details to receive a free quote.
                                Let us make turning your car into cash easy and
                                efficient—list your vehicle with us today!
                            </p>
                        </div>
                    </div>
                </div>
                <div className="w-[1064px] min-h-[200px] bg-white rounded-3xl shadow-xl px-[28px] py-[34px] mb-6">
                    <div>
                        <h1 className="text-secondary text-xl font-bold pt-4">
                            Mission
                        </h1>
                        <div className="flex-col flex gap-5 mt-4  text-base md:text-lg">
                            <p>
                                At Wheeliyo, our mission is to transform the
                                car-selling experience by providing a seamless,
                                efficient, and rewarding process for every
                                customer. We are committed to delivering the
                                best deals and prices through a user-friendly
                                platform that ensures minimal wait time and
                                hassle-free transactions. Our goal is to make
                                selling your car as straightforward and
                                profitable as possible while maintaining the
                                highest standards of professionalism and trust.
                            </p>
                        </div>
                    </div>
                </div>
                <div className="w-[1064px] min-h-[200px] bg-white rounded-3xl shadow-xl px-[28px] py-[34px]">
                    <div>
                        <h1 className="text-secondary text-xl font-bold pt-4">
                            Vision
                        </h1>
                        <div className="flex-col flex gap-5 mt-4  text-base md:text-lg">
                            <p>
                                Our vision is to be the leading platform for car
                                sales, recognized for our innovative approach
                                and dedication to customer satisfaction. We aim
                                to continually enhance our services and expand
                                our reach, connecting car sellers with potential
                                buyers through cutting-edge technology and
                                exceptional support. By setting new benchmarks
                                in the industry, we strive to empower
                                individuals to achieve the best value for their
                                vehicles and redefine the car-selling experience
                                for the future.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <section id="get-in-touch" className="pt-[47px]">
                <ReadyToSellPage />
            </section>
            <section className="lg:h-[195px] bottom-0">
                <Footer />
            </section>
        </div>
    )
}

export default TermsAndConditions
