import Header from 'components/header/Header'
import Head from 'next/head'
import Footer from 'components/sections/footer'
import ReadyToSellPage from 'components/sections/readyToSell'

const TermsAndConditions = () => {
    return (
        <div>
            <Head>
                <title>Wheeliyo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className="relative">
                <img
                    alt="bg"
                    className="w-screen"
                    src="/assets/privacy-policy-bg.svg"
                />
                <div className="absolute-center text-white text-center">
                    <h1 className="xl:text-3xl text-base xl:mb-2 md:text-xl">
                        Terms and conditions
                    </h1>
                </div>
            </div>
            <div className="flex justify-center items-center px-4 lg:px-10">
                <div className="w-[1064px] min-h-[200px] bg-white rounded-3xl shadow-xl px-[28px] py-[34px]">
                    <div>
                        <h1 className="text-secondary text-xl font-bold pt-4">
                            Terms and conditions
                        </h1>
                        <div className="flex-col flex gap-5 mt-4  text-base md:text-lg">
                            <p className="font-semibold">1. Introduction</p>
                            <p>
                                Welcome to Wheeliyo! By accessing or using our
                                website, you agree to comply with and be bound
                                by these Terms and Conditions. If you do not
                                agree to these terms, please do not use our
                                services.
                            </p>

                            <p className="font-semibold">2. Services</p>
                            <p>
                                Wheeliyo provides a platform for selling cars by
                                offering competitive deals and prices. We
                                facilitate the process through online offers,
                                doorstep evaluations, and direct interactions
                                with potential buyers.
                            </p>

                            <p className="font-semibold">3. User Obligations</p>
                            <p>
                                Eligibility: You must be at least 18 years old
                                and legally able to enter into contracts to use
                                our services. Accuracy of Information: You agree
                                to provide accurate and complete information
                                about your vehicle. Wheeliyo is not responsible
                                for errors or discrepancies in the information
                                you provide.
                            </p>
                            <p>
                                Use of Service: You agree to use our services
                                only for lawful purposes and in accordance with
                                these Terms and Conditions.
                            </p>

                            <p className="font-semibold">
                                4. Offers and Transactions
                            </p>
                            <p>
                                Offers: Offers are generated based on the
                                details you provide and current market
                                conditions. Offers are subject to change and may
                                not be guaranteed.
                            </p>
                            <p>
                                Evaluation and Sale: Our team will conduct a
                                doorstep evaluation of your vehicle. Final
                                offers may vary based on the physical
                                inspection.
                            </p>

                            <p className="font-semibold">
                                5. Payments and Refunds
                            </p>
                            <p>
                                Payments: Payments will be processed as per the
                                agreed terms upon successful completion of the
                                transaction.
                            </p>
                            <p>
                                Refunds: Refunds are not applicable as
                                transactions are based on the sale of
                                goods/services rather than prepayments.
                            </p>
                            <p className="font-semibold">
                                6. Intellectual Property
                            </p>

                            <p>
                                All content on the Wheeliyo website, including
                                text, graphics, logos, and images, is the
                                property of Wheeliyo or its content suppliers
                                and is protected by intellectual property laws.
                            </p>

                            <p className="font-semibold">
                                7. Limitation of Liability
                            </p>
                            <p>
                                Wheeliyo is not liable for any indirect,
                                incidental, or consequential damages arising
                                from your use of our services. Our liability is
                                limited to the maximum extent permitted by law.
                            </p>

                            <p className="font-semibold">8. Modifications</p>
                            <p>
                                Wheeliyo reserves the right to modify these
                                Terms and Conditions at any time. Changes will
                                be effective when posted on our website.
                            </p>

                            <p className="font-semibold">9. Governing Law</p>
                            <p>
                                These Terms and Conditions are governed by and
                                construed in accordance with the laws of India.
                                Any disputes arising from these terms shall be
                                resolved in the courts of india.
                            </p>

                            <p className="font-semibold">10. Contact Us</p>
                            <p>
                                For any questions or concerns regarding these
                                Terms and Conditions, please contact us at [{' '}
                                <a href={`tel:9840217225`}>9840217225</a> /{' '}
                                <a href={`mailto:smurali@wheeliyo.com`}>
                                    smurali@wheeliyo.com
                                </a>
                                ].
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <section id="get-in-touch" className="pt-[47px]">
                <ReadyToSellPage />
            </section>
            <section className="lg:h-[195px] bottom-0">
                <Footer />
            </section>
        </div>
    )
}

export default TermsAndConditions
